import Foundation

/// Cross-package-manager bundle accessor for SDK resources (e.g. mraid.js).
///
/// Three compile-time cases, determined by build system flags:
///
/// 1. CocoaPods source build (`:path`)
///    Compiler flag: `-DCOCOAPODS` (set by CocoaPods for all pod targets)
///    Resources:     CocoaPods copies them as `CDAds_MRAID.bundle` into Bundle.main
///    Fallback:      Binary CocoaPods (`vendored_frameworks`) re-runs the XCFramework binary
///                   which was built without -DCOCOAPODS, so it hits case 3 instead.
///
/// 2. SPM source build (`.target`)
///    Compiler flag: `SWIFT_PACKAGE` (set automatically by SPM / Xcode SPM resolver)
///    Resources:     Bundle.module (auto-generated accessor)
///
/// 3. XCFramework binary (Xcode archive / SPM `.binaryTarget` / CocoaPods `vendored_frameworks`)
///    Compiler flags: neither COCOAPODS nor SWIFT_PACKAGE are defined at archive time
///    Resources:      Must be embedded inside the .framework bundle at XCFramework build time.
///                    Accessed via Bundle(for:) — returns the framework's own bundle at runtime.
internal extension Bundle {

    /// - Parameter cocoapodsBundleName: the `s.resource_bundles` key in `CDAds.podspec` that
    ///   contains the resource being looked up. Only consulted in the CocoaPods source-build
    ///   case — SPM's `Bundle.module` and the XCFramework binary's `Bundle(for:)` each already
    ///   resolve to a single bundle covering every resource regardless of which subfolder it
    ///   came from, so the name only matters when CocoaPods has split resources into several
    ///   separately-named `.bundle`s under `Bundle.main`.
    static func cdads(_ cocoapodsBundleName: String) -> Bundle {
#if COCOAPODS
        // Case 1a: CocoaPods static-library pod — resource bundle is copied directly
        // into the app's main bundle.
        if let url = Bundle.main.url(forResource: cocoapodsBundleName, withExtension: "bundle"),
           let bundle = Bundle(url: url) {
            return bundle
        }
        // Case 1b: CocoaPods dynamic-framework pod (`use_frameworks!` — always the case
        // for Flutter plugins). The resource bundle isn't copied to Bundle.main at all;
        // it's nested inside CDAds.framework itself, e.g.
        // Runner.app/Frameworks/CDAds.framework/CDAds_Resources.bundle.
        let frameworkBundle = Bundle(for: _CDAdsBundle.self)
        if let url = frameworkBundle.url(forResource: cocoapodsBundleName, withExtension: "bundle"),
           let bundle = Bundle(url: url) {
            return bundle
        }
        return frameworkBundle
#elseif SWIFT_PACKAGE
        // Case 2: SPM source build — Bundle.module is auto-generated by the build system.
        return Bundle.module
#else
        // Case 3: XCFramework binary (Xcode archive / binaryTarget / vendored_frameworks).
        // Resources are embedded inside the .framework bundle; Bundle(for:) locates it
        // via the Objective-C runtime using any class defined in this module.
        return Bundle(for: _CDAdsBundle.self)
#endif
    }
}

/// Marker class used solely so `Bundle(for:)` can locate the framework bundle.
/// Must be a class (not a value type) for the Obj-C runtime bundle lookup to work.
private final class _CDAdsBundle {}
